version: "3.9"

networks:
    traefik_network:
        external: true

services:

    api:
        container_name: projlix-api
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            args:
                BUILD_APP_ENV: "local"
        image: projlix-api
        environment:
            XDG_CONFIG_HOME: "/var/www/html/.tinker"
        user: $USERID
        env_file: .env
        volumes:
            - .:/var/www/html:cached
            - ./docker/php/local/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
            - ./docker/php/local/php.ini:/usr/local/etc/php/php.ini
        networks:
            - traefik_network

    scheduler:
        image: projlix-api
        container_name: projlix-scheduler
        volumes:
            - .:/var/www/html
            - ./docker/scheduler/supervisord.conf:/etc/supervisord-scheduler.conf
        user: $USERID
        env_file: .env
        networks:
            - traefik_network
        depends_on:
            - api
        entrypoint:
          ["/usr/bin/supervisord", "-n", "-c", "/etc/supervisord-scheduler.conf"]

    nginx:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        container_name: projlix-nginx
        volumes:
            - .:/var/www/html:cached
        depends_on:
            - api
        networks:
            - traefik_network
        entrypoint: sh -c "sed -i 's/api:9000/projlix-api:9000/g' /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.projlix-api.rule=Host(`api-projlix.docker.localhost`)"
            - "traefik.http.services.projlix-api.loadbalancer.server.port=8080"
            - "traefik.http.routers.projlix-api.tls=true"

    supervisord-email:
        image: projlix-api
        container_name: projlix-supervisord-email
        volumes:
            - .:/var/www/html:cached
            - ./docker/php/supervisord/email.conf:/etc/supervisord/email.conf
        networks:
            - traefik_network
        user: root
        env_file: .env
        depends_on:
            - api
        entrypoint:
          [ "/usr/bin/supervisord", "-n", "-c", "/etc/supervisord/email.conf" ]
