<?php

namespace App\Shared\Enums;

enum RulesEnum: string
{
    case USERS_TECHNICAL_SUPPORT_UPDATE_STATUS = 'USERS_TECHNICAL_SUPPORT_UPDATE_STATUS';
    case USERS_ADMIN_MASTER_UPDATE_STATUS = 'USERS_ADMIN_MASTER_UPDATE_STATUS';

    case ADMIN_USERS_VIEW   = 'ADMIN_USERS_VIEW';
    case ADMIN_USERS_INSERT = 'ADMIN_USERS_INSERT';
    case ADMIN_USERS_UPDATE = 'ADMIN_USERS_UPDATE';

    case PROFILES_ADMIN_MASTER_VIEW    = 'PROFILES_ADMIN_MASTER_VIEW';
    case PROFILES_PROJECT_MANAGER_VIEW = 'PROFILES_PROJECT_MANAGER_VIEW';
    case PROFILES_TEAM_LEADER_VIEW     = 'PROFILES_TEAM_LEADER_VIEW';
    case PROFILES_PROJECT_MEMBER_VIEW  = 'PROFILES_PROJECT_MEMBER_VIEW';

    case CITIES_VIEW = 'CITIES_VIEW';
    case STATES_VIEW = 'STATES_VIEW';
    case SYSTEM_VIEW = 'SYSTEM_VIEW';
    case SYSTEM_UPDATE = 'SYSTEM_UPDATE';

    case POSITIONS_VIEW = 'POSITIONS_VIEW';
    case POSITIONS_INSERT = 'POSITIONS_INSERT';
    case POSITIONS_UPDATE = 'POSITIONS_UPDATE';
    case POSITIONS_DELETE = 'POSITIONS_DELETE';

    case PROJECTS_ADMIN_MASTER_VIEW = 'PROJECTS_ADMIN_MASTER_VIEW';
    case PROJECTS_ADMIN_MASTER_INSERT = 'PROJECTS_ADMIN_MASTER_INSERT';
    case PROJECTS_ADMIN_MASTER_UPDATE = 'PROJECTS_ADMIN_MASTER_UPDATE';
    case PROJECTS_ADMIN_MASTER_DELETE = 'PROJECTS_ADMIN_MASTER_DELETE';

    case PROJECTS_PROJECT_MANAGER_VIEW = 'PROJECTS_PROJECT_MANAGER_VIEW';
    case PROJECTS_PROJECT_MANAGER_INSERT = 'PROJECTS_PROJECT_MANAGER_INSERT';
    case PROJECTS_PROJECT_MANAGER_UPDATE = 'PROJECTS_PROJECT_MANAGER_UPDATE';

    case PROJECTS_TEAM_LEADER_VIEW = 'PROJECTS_TEAM_LEADER_VIEW';
    case PROJECTS_TEAM_LEADER_INSERT = 'PROJECTS_TEAM_LEADER_INSERT';
    case PROJECTS_TEAM_LEADER_UPDATE = 'PROJECTS_TEAM_LEADER_UPDATE';

    case PROJECTS_PROJECT_MEMBER_VIEW = 'PROJECTS_PROJECT_MEMBER_VIEW';

    case TEAM_USERS_ADMIN_MASTER_VIEW = 'TEAM_USERS_ADMIN_MASTER_VIEW';
    case TEAM_USERS_ADMIN_MASTER_INSERT = 'TEAM_USERS_ADMIN_MASTER_INSERT';
    case TEAM_USERS_ADMIN_MASTER_UPDATE = 'TEAM_USERS_ADMIN_MASTER_UPDATE';
    case TEAM_USERS_ADMIN_MASTER_DELETE = 'TEAM_USERS_ADMIN_MASTER_DELETE';

    case TEAM_USERS_PROJECT_MANAGER_VIEW = 'TEAM_USERS_PROJECT_MANAGER_VIEW';
    case TEAM_USERS_PROJECT_MANAGER_INSERT = 'TEAM_USERS_PROJECT_MANAGER_INSERT';
    case TEAM_USERS_PROJECT_MANAGER_UPDATE = 'TEAM_USERS_PROJECT_MANAGER_UPDATE';
    case TEAM_USERS_PROJECT_MANAGER_DELETE = 'TEAM_USERS_PROJECT_MANAGER_DELETE';

    case TEAM_USERS_TEAM_LEADER_VIEW = 'TEAM_USERS_TEAM_LEADER_VIEW';
    case TEAM_USERS_TEAM_LEADER_INSERT = 'TEAM_USERS_TEAM_LEADER_INSERT';
    case TEAM_USERS_TEAM_LEADER_UPDATE = 'TEAM_USERS_TEAM_LEADER_UPDATE';

    case TEAM_USERS_PROJECT_MEMBER_VIEW = 'TEAM_USERS_PROJECT_MEMBER_VIEW';

    case NOTES_VIEW   = 'NOTES_VIEW';
    case NOTES_INSERT  = 'NOTES_INSERT';
    case NOTES_UPDATE = 'NOTES_UPDATE';
    case NOTES_DELETE = 'NOTES_DELETE';

    case COLORS_VIEW   = 'COLORS_VIEW';
    case ICONS_VIEW   = 'ICONS_VIEW';

    case TAGS_VIEW = 'TAGS_VIEW';
    case TAGS_INSERT = 'TAGS_INSERT';
    case TAGS_UPDATE = 'TAGS_UPDATE';
    case TAGS_DELETE = 'TAGS_DELETE';

    case SECTIONS_ADMIN_MASTER_VIEW      = 'SECTIONS_ADMIN_MASTER_VIEW';
    case SECTIONS_ADMIN_MASTER_INSERT    = 'SECTIONS_ADMIN_MASTER_INSERT';
    case SECTIONS_ADMIN_MASTER_UPDATE    = 'SECTIONS_ADMIN_MASTER_UPDATE';
    case SECTIONS_ADMIN_MASTER_DELETE    = 'SECTIONS_ADMIN_MASTER_DELETE';

    case SECTIONS_PROJECT_MANAGER_VIEW   = 'SECTIONS_PROJECT_MANAGER_VIEW';
    case SECTIONS_PROJECT_MANAGER_INSERT = 'SECTIONS_PROJECT_MANAGER_INSERT';
    case SECTIONS_PROJECT_MANAGER_UPDATE = 'SECTIONS_PROJECT_MANAGER_UPDATE';
    case SECTIONS_PROJECT_MANAGER_DELETE = 'SECTIONS_PROJECT_MANAGER_DELETE';

    case SECTIONS_TEAM_LEADER_VIEW       = 'SECTIONS_TEAM_LEADER_VIEW';
    case SECTIONS_TEAM_LEADER_INSERT     = 'SECTIONS_TEAM_LEADER_INSERT';
    case SECTIONS_TEAM_LEADER_UPDATE     = 'SECTIONS_TEAM_LEADER_UPDATE';
    case SECTIONS_TEAM_LEADER_DELETE     = 'SECTIONS_TEAM_LEADER_DELETE';

    case SECTIONS_PROJECT_MEMBER_VIEW    = 'SECTIONS_PROJECT_MEMBER_VIEW';

    case CARDS_ADMIN_MASTER_VIEW = 'CARDS_ADMIN_MASTER_VIEW';
    case CARDS_ADMIN_MASTER_INSERT = 'CARDS_ADMIN_MASTER_INSERT';
    case CARDS_ADMIN_MASTER_UPDATE = 'CARDS_ADMIN_MASTER_UPDATE';
    case CARDS_ADMIN_MASTER_DELETE = 'CARDS_ADMIN_MASTER_DELETE';

    case CARDS_PROJECT_MANAGER_VIEW = 'CARDS_PROJECT_MANAGER_VIEW';
    case CARDS_PROJECT_MANAGER_INSERT = 'CARDS_PROJECT_MANAGER_INSERT';
    case CARDS_PROJECT_MANAGER_UPDATE = 'CARDS_PROJECT_MANAGER_UPDATE';
    case CARDS_PROJECT_MANAGER_DELETE = 'CARDS_PROJECT_MANAGER_DELETE';

    case CARDS_TEAM_LEADER_VIEW = 'CARDS_TEAM_LEADER_VIEW';
    case CARDS_TEAM_LEADER_INSERT = 'CARDS_TEAM_LEADER_INSERT';
    case CARDS_TEAM_LEADER_UPDATE = 'CARDS_TEAM_LEADER_UPDATE';
    case CARDS_TEAM_LEADER_DELETE = 'CARDS_TEAM_LEADER_DELETE';

    case CARDS_PROJECT_MEMBER_VIEW = 'CARDS_PROJECT_MEMBER_VIEW';
    case CARDS_PROJECT_MEMBER_INSERT = 'CARDS_PROJECT_MEMBER_INSERT';
    case CARDS_PROJECT_MEMBER_UPDATE = 'CARDS_PROJECT_MEMBER_UPDATE';
    case CARDS_PROJECT_MEMBER_DELETE = 'CARDS_PROJECT_MEMBER_DELETE';
}
